    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"
   
    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 7.4
      apt: name=php7.4 state=present

    - name: install lamp stack
      apt:
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes

    - name: Ansible delete file example
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Clone a github repository
      git:
        repo: https://github.com/kanform/heval
        dest: /var/www/html/
        clone: yes
        force: true     
